name: Build Flet APK with Debug

on:
  push:
    branches:
      - main

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
    # Step 1: 檢出程式碼
    - name: 檢出程式碼
      uses: actions/checkout@v3

    # Step 2: 安裝 Python 環境
    - name: 安裝 Python 環境
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    # Step 3: 安裝必要的構建工具
    - name: 安裝構建工具
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential ninja-build python3-dev libopenblas-dev gfortran cmake openjdk-11-jdk

    # Step 4: 安裝 Flutter
    - name: 安裝 Flutter
      run: |
        git clone https://github.com/flutter/flutter.git -b stable
        echo "${{ github.workspace }}/flutter/bin" >> $GITHUB_PATH
        echo "${{ github.workspace }}/flutter/bin/cache/dart-sdk/bin" >> $GITHUB_PATH
        export PATH="$PATH:${{ github.workspace }}/flutter/bin"
        flutter --version

    # Step 5: 安裝 Flet 和依賴
    - name: 安裝 Flet 和依賴
      run: |
        pip install -r requirements.txt
        pip install flet

    # Step 6: 打包 APK
    - name: 打包 APK
      run: |
        flet build apk  

    # Step 7: 上傳構建日誌
    - name: 上傳日誌
      uses: actions/upload-artifact@v3
      with:
        name: build-logs
        path: |
          build_log.txt
