name: Build and Debug Flet APK

on:
  push:
    branches:
      - main

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out code
      - name: Check out code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Step 3: Install necessary build tools
      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential ninja-build python3-dev libopenblas-dev gfortran cmake openjdk-11-jdk

      # Step 4: Install Flutter using Flutter Action
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.6'  # Specify the exact Flutter version

      # Step 5: Verify Flutter installation
      - name: Flutter Doctor
        run: flutter doctor -v

      # Step 6: Install Cython, Flet, and dependencies
      - name: Install Cython, Flet, and dependencies
        run: |
          pip install --upgrade pip
          pip install cython
          pip install -r requirements.txt
          pip install flet

      # Step 7: Get Flutter dependencies
      - name: Get Flutter dependencies
        run: flutter pub get

      # Step 8: Build APK
      - name: Build APK
        run: |
          flet build apk > build_log.txt 2>&1
        continue-on-error: true  # Continue even if this step fails

      # Step 9: Upload build logs
      - name: Upload logs
        uses: actions/upload-artifact@v3
        with:
          name: build-logs
          path: |
            build_log.txt
