name: Build Flet APK

on:
  push:
    branches:
      - main  # 監聽 main 分支的變更

jobs:
  build-apk:
    runs-on: ubuntu-latest  # 使用 Ubuntu 作為執行環境

    steps:
    - name: 檢出程式碼
      uses: actions/checkout@v3

    - name: 安裝 Python 環境
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: 安裝 Flutter
      run: |
        git clone https://github.com/flutter/flutter.git -b stable
        echo "${{ github.workspace }}/flutter/bin" >> $GITHUB_PATH
        flutter --version

    - name: 安裝必要套件
      run: |
        python -m pip install --upgrade pip
        pip install flet flet-cli numpy opencv-python flask

    - name: 打包 APK
      run: |
        flet build apk

    - name: 上傳 APK 為 Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: flet-apk
        path: build/app/outputs/apk/release/  # 確保此路徑與實際輸出路徑一致
