name: Flutter Build APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 检出仓库代码
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. 设置 Flutter 环境
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.13.6' # 根据需要更改 Flutter 版本
          architecture: 'x64'
          cache: true

      # 3. 验证 Flutter 安装
      - name: Flutter Doctor
        run: flutter doctor -v

      # 4. 安装依赖项
      - name: Install dependencies
        run: flutter pub get

      # 5. 构建 APK
      - name: Build APK
        run: flutter build apk --release

      # 6. 上传 APK 作为构建产物
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk
