name: Build Flet APK

on:
  push:
    branches:
      - main  # 監聽 main 分支的變更，您可以改成其他分支名稱

jobs:
  build-apk:
    runs-on: ubuntu-latest  # 使用 Ubuntu 作為執行環境

    steps:
    - name: 檢出程式碼
      uses: actions/checkout@v3

    - name: 設定 Python 環境
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"  # 確保 Python 版本支援 Flet

    - name: 安裝必要套件
      run: |
        python -m pip install --upgrade pip
        pip install flet flet-cli numpy opencv-python flask

    - name: 打包 APK
      run: |
        flet build apk

    - name: 上傳 APK 為 Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: flet-apk
        path: build/app/outputs/apk/release/  # 調整為 APK 輸出的實際路徑
