name: Build Flet APK

on:
  push:
    branches:
      - main

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
    - name: 檢出程式碼
      uses: actions/checkout@v3

    - name: 安裝 Python 環境
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: 安裝構建工具
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential python3-dev libopenblas-dev gfortran cmake

    - name: 升級 pip 和相關工具
      run: |
        python -m pip install --upgrade pip setuptools wheel

    - name: 安裝依賴並捕獲日誌
      run: |
        pip install -r requirements.txt --verbose

    - name: 安裝 Flutter
      run: |
        git clone https://github.com/flutter/flutter.git -b stable
        export PATH="$PATH:${{ github.workspace }}/flutter/bin"
        flutter precache --android --force
        flutter doctor

    - name: 打包 APK
      run: |
        export PATH="$PATH:${{ github.workspace }}/flutter/bin"
        flet build apk

    - name: 上傳 APK
      uses: actions/upload-artifact@v3
      with:
        name: flet-apk
        path: build/app/outputs/apk/release/
